/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'author' : IDL.Principal,
  'postId' : PostId,
});
export const Platform = IDL.Variant({
  'Wattpad' : IDL.Null,
  'Netflix' : IDL.Null,
  'Bato' : IDL.Null,
  'Viki' : IDL.Null,
  'Webtoon' : IDL.Null,
  'YouTube' : IDL.Null,
  'Spotify' : IDL.Null,
  'MangaDex' : IDL.Null,
  'Tapas' : IDL.Null,
  'SoundCloud' : IDL.Null,
  'Other' : IDL.Text,
  'Tappytoon' : IDL.Null,
  'Lezhin' : IDL.Null,
});
export const Category = IDL.Variant({
  'MANHWA' : IDL.Null,
  'BTS_LIVE' : IDL.Null,
  'K_DRAMA' : IDL.Null,
  'BTS_SONGS' : IDL.Null,
  'FANFICTION' : IDL.Null,
});
export const Genre = IDL.Variant({
  'AU' : IDL.Null,
  'EDM' : IDL.Null,
  'Pop' : IDL.Null,
  'Rap' : IDL.Null,
  'RnB' : IDL.Null,
  'Action' : IDL.Null,
  'Mystery' : IDL.Null,
  'Historical' : IDL.Null,
  'Drama' : IDL.Null,
  'Ballad' : IDL.Null,
  'HipHop' : IDL.Null,
  'Romance' : IDL.Null,
  'Fantasy' : IDL.Null,
  'Thriller' : IDL.Null,
  'Comedy' : IDL.Null,
});
export const ContentLanguage = IDL.Variant({
  'Korean' : IDL.Null,
  'Spanish' : IDL.Null,
  'Hindi' : IDL.Null,
  'English' : IDL.Null,
  'French' : IDL.Null,
});
export const LinkId = IDL.Nat;
export const Link = IDL.Record({
  'id' : LinkId,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'contentLanguage' : IDL.Opt(ContentLanguage),
  'description' : IDL.Text,
  'platform' : Platform,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'genre' : IDL.Opt(Genre),
  'addedAt' : Timestamp,
  'addedBy' : IDL.Principal,
  'category' : Category,
  'coverPhotoUrl' : IDL.Opt(IDL.Text),
});
export const WatchlistInput = IDL.Record({ 'linkId' : LinkId });
export const WatchlistEntryView = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Text,
  'addedAt' : Timestamp,
  'linkId' : IDL.Text,
});
export const PostView = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'author' : IDL.Principal,
  'likesCount' : IDL.Nat,
  'flagged' : IDL.Bool,
});
export const ProfileView = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'preferredLanguage' : IDL.Opt(ContentLanguage),
  'country' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'joinedAt' : Timestamp,
  'subtitlePreference' : IDL.Bool,
  'profileCompleted' : IDL.Bool,
  'fandom' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
  'addLink' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Platform,
        Category,
        IDL.Opt(Genre),
        IDL.Opt(ContentLanguage),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Link],
      [],
    ),
  'addToWatchlist' : IDL.Func(
      [WatchlistInput],
      [IDL.Variant({ 'ok' : WatchlistEntryView, 'err' : IDL.Text })],
      [],
    ),
  'createPost' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [PostView], []),
  'deleteLink' : IDL.Func([LinkId], [IDL.Bool], []),
  'editLink' : IDL.Func(
      [
        LinkId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Platform,
        Category,
        IDL.Opt(Genre),
        IDL.Opt(ContentLanguage),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
  'flagPost' : IDL.Func([PostId], [IDL.Bool], []),
  'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getLinks' : IDL.Func([IDL.Opt(Category)], [IDL.Vec(Link)], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(PostView)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(ProfileView)], ['query']),
  'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistEntryView)], ['query']),
  'isInWatchlist' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [IDL.Bool], []),
  'listPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'searchByGenre' : IDL.Func([Genre], [IDL.Vec(Link)], ['query']),
  'searchByLanguage' : IDL.Func([ContentLanguage], [IDL.Vec(Link)], ['query']),
  'searchLinks' : IDL.Func([IDL.Text], [IDL.Vec(Link)], ['query']),
  'setOnboarding' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(ContentLanguage),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'setProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'author' : IDL.Principal,
    'postId' : PostId,
  });
  const Platform = IDL.Variant({
    'Wattpad' : IDL.Null,
    'Netflix' : IDL.Null,
    'Bato' : IDL.Null,
    'Viki' : IDL.Null,
    'Webtoon' : IDL.Null,
    'YouTube' : IDL.Null,
    'Spotify' : IDL.Null,
    'MangaDex' : IDL.Null,
    'Tapas' : IDL.Null,
    'SoundCloud' : IDL.Null,
    'Other' : IDL.Text,
    'Tappytoon' : IDL.Null,
    'Lezhin' : IDL.Null,
  });
  const Category = IDL.Variant({
    'MANHWA' : IDL.Null,
    'BTS_LIVE' : IDL.Null,
    'K_DRAMA' : IDL.Null,
    'BTS_SONGS' : IDL.Null,
    'FANFICTION' : IDL.Null,
  });
  const Genre = IDL.Variant({
    'AU' : IDL.Null,
    'EDM' : IDL.Null,
    'Pop' : IDL.Null,
    'Rap' : IDL.Null,
    'RnB' : IDL.Null,
    'Action' : IDL.Null,
    'Mystery' : IDL.Null,
    'Historical' : IDL.Null,
    'Drama' : IDL.Null,
    'Ballad' : IDL.Null,
    'HipHop' : IDL.Null,
    'Romance' : IDL.Null,
    'Fantasy' : IDL.Null,
    'Thriller' : IDL.Null,
    'Comedy' : IDL.Null,
  });
  const ContentLanguage = IDL.Variant({
    'Korean' : IDL.Null,
    'Spanish' : IDL.Null,
    'Hindi' : IDL.Null,
    'English' : IDL.Null,
    'French' : IDL.Null,
  });
  const LinkId = IDL.Nat;
  const Link = IDL.Record({
    'id' : LinkId,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'contentLanguage' : IDL.Opt(ContentLanguage),
    'description' : IDL.Text,
    'platform' : Platform,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'genre' : IDL.Opt(Genre),
    'addedAt' : Timestamp,
    'addedBy' : IDL.Principal,
    'category' : Category,
    'coverPhotoUrl' : IDL.Opt(IDL.Text),
  });
  const WatchlistInput = IDL.Record({ 'linkId' : LinkId });
  const WatchlistEntryView = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Text,
    'addedAt' : Timestamp,
    'linkId' : IDL.Text,
  });
  const PostView = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'author' : IDL.Principal,
    'likesCount' : IDL.Nat,
    'flagged' : IDL.Bool,
  });
  const ProfileView = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'preferredLanguage' : IDL.Opt(ContentLanguage),
    'country' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'joinedAt' : Timestamp,
    'subtitlePreference' : IDL.Bool,
    'profileCompleted' : IDL.Bool,
    'fandom' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
    'addLink' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Platform,
          Category,
          IDL.Opt(Genre),
          IDL.Opt(ContentLanguage),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Link],
        [],
      ),
    'addToWatchlist' : IDL.Func(
        [WatchlistInput],
        [IDL.Variant({ 'ok' : WatchlistEntryView, 'err' : IDL.Text })],
        [],
      ),
    'createPost' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [PostView], []),
    'deleteLink' : IDL.Func([LinkId], [IDL.Bool], []),
    'editLink' : IDL.Func(
        [
          LinkId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Platform,
          Category,
          IDL.Opt(Genre),
          IDL.Opt(ContentLanguage),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
    'flagPost' : IDL.Func([PostId], [IDL.Bool], []),
    'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getLinks' : IDL.Func([IDL.Opt(Category)], [IDL.Vec(Link)], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(PostView)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(ProfileView)], ['query']),
    'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistEntryView)], ['query']),
    'isInWatchlist' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [IDL.Bool], []),
    'listPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'searchByGenre' : IDL.Func([Genre], [IDL.Vec(Link)], ['query']),
    'searchByLanguage' : IDL.Func(
        [ContentLanguage],
        [IDL.Vec(Link)],
        ['query'],
      ),
    'searchLinks' : IDL.Func([IDL.Text], [IDL.Vec(Link)], ['query']),
    'setOnboarding' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(ContentLanguage),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'setProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };