/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'MANHWA' : null } |
  { 'BTS_LIVE' : null } |
  { 'K_DRAMA' : null } |
  { 'BTS_SONGS' : null } |
  { 'FANFICTION' : null };
export interface Comment {
  'id' : CommentId,
  'content' : string,
  'createdAt' : Timestamp,
  'author' : Principal,
  'postId' : PostId,
}
export type CommentId = bigint;
export type ContentLanguage = { 'Korean' : null } |
  { 'Spanish' : null } |
  { 'Hindi' : null } |
  { 'English' : null } |
  { 'French' : null };
export type Genre = { 'AU' : null } |
  { 'EDM' : null } |
  { 'Pop' : null } |
  { 'Rap' : null } |
  { 'RnB' : null } |
  { 'Action' : null } |
  { 'Mystery' : null } |
  { 'Historical' : null } |
  { 'Drama' : null } |
  { 'Ballad' : null } |
  { 'HipHop' : null } |
  { 'Romance' : null } |
  { 'Fantasy' : null } |
  { 'Thriller' : null } |
  { 'Comedy' : null };
export interface Link {
  'id' : LinkId,
  'url' : string,
  'title' : string,
  'contentLanguage' : [] | [ContentLanguage],
  'description' : string,
  'platform' : Platform,
  'mediaUrl' : [] | [string],
  'genre' : [] | [Genre],
  'addedAt' : Timestamp,
  'addedBy' : Principal,
  'category' : Category,
  'coverPhotoUrl' : [] | [string],
}
export type LinkId = bigint;
export type Platform = { 'Wattpad' : null } |
  { 'Netflix' : null } |
  { 'Bato' : null } |
  { 'Viki' : null } |
  { 'Webtoon' : null } |
  { 'YouTube' : null } |
  { 'Spotify' : null } |
  { 'MangaDex' : null } |
  { 'Tapas' : null } |
  { 'SoundCloud' : null } |
  { 'Other' : string } |
  { 'Tappytoon' : null } |
  { 'Lezhin' : null };
export type PostId = bigint;
export interface PostView {
  'id' : PostId,
  'content' : string,
  'hashtags' : Array<string>,
  'createdAt' : Timestamp,
  'author' : Principal,
  'likesCount' : bigint,
  'flagged' : boolean,
}
export interface ProfileView {
  'bio' : string,
  'principal' : Principal,
  'preferredLanguage' : [] | [ContentLanguage],
  'country' : [] | [string],
  'username' : string,
  'joinedAt' : Timestamp,
  'subtitlePreference' : boolean,
  'profileCompleted' : boolean,
  'fandom' : [] | [string],
}
export type Timestamp = bigint;
export interface WatchlistEntryView {
  'id' : string,
  'owner' : string,
  'addedAt' : Timestamp,
  'linkId' : string,
}
export interface WatchlistInput { 'linkId' : LinkId }
export interface _SERVICE {
  'addComment' : ActorMethod<[PostId, string], Comment>,
  'addLink' : ActorMethod<
    [
      string,
      string,
      string,
      Platform,
      Category,
      [] | [Genre],
      [] | [ContentLanguage],
      [] | [string],
      [] | [string],
    ],
    Link
  >,
  'addToWatchlist' : ActorMethod<
    [WatchlistInput],
    { 'ok' : WatchlistEntryView } |
      { 'err' : string }
  >,
  'createPost' : ActorMethod<[string, Array<string>], PostView>,
  'deleteLink' : ActorMethod<[LinkId], boolean>,
  'editLink' : ActorMethod<
    [
      LinkId,
      string,
      string,
      string,
      Platform,
      Category,
      [] | [Genre],
      [] | [ContentLanguage],
      [] | [string],
      [] | [string],
    ],
    boolean
  >,
  'flagPost' : ActorMethod<[PostId], boolean>,
  'getComments' : ActorMethod<[PostId], Array<Comment>>,
  'getLinks' : ActorMethod<[[] | [Category]], Array<Link>>,
  'getPost' : ActorMethod<[PostId], [] | [PostView]>,
  'getProfile' : ActorMethod<[Principal], [] | [ProfileView]>,
  'getWatchlist' : ActorMethod<[], Array<WatchlistEntryView>>,
  'isInWatchlist' : ActorMethod<[string], boolean>,
  'likePost' : ActorMethod<[PostId], boolean>,
  'listPosts' : ActorMethod<[], Array<PostView>>,
  'removeFromWatchlist' : ActorMethod<[string], boolean>,
  'searchByGenre' : ActorMethod<[Genre], Array<Link>>,
  'searchByLanguage' : ActorMethod<[ContentLanguage], Array<Link>>,
  'searchLinks' : ActorMethod<[string], Array<Link>>,
  'setOnboarding' : ActorMethod<
    [[] | [string], [] | [string], [] | [ContentLanguage], boolean],
    undefined
  >,
  'setProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];