/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type CommentId = bigint;
export interface WatchlistInput {
    linkId: LinkId;
}
export interface WatchlistEntryView {
    id: string;
    owner: string;
    addedAt: Timestamp;
    linkId: string;
}
export type PostId = bigint;
export interface PostView {
    id: PostId;
    content: string;
    hashtags: Array<string>;
    createdAt: Timestamp;
    author: Principal;
    likesCount: bigint;
    flagged: boolean;
}
export interface Comment {
    id: CommentId;
    content: string;
    createdAt: Timestamp;
    author: Principal;
    postId: PostId;
}
export type Platform = {
    __kind__: "Wattpad";
    Wattpad: null;
} | {
    __kind__: "Netflix";
    Netflix: null;
} | {
    __kind__: "Bato";
    Bato: null;
} | {
    __kind__: "Viki";
    Viki: null;
} | {
    __kind__: "Webtoon";
    Webtoon: null;
} | {
    __kind__: "YouTube";
    YouTube: null;
} | {
    __kind__: "Spotify";
    Spotify: null;
} | {
    __kind__: "MangaDex";
    MangaDex: null;
} | {
    __kind__: "Tapas";
    Tapas: null;
} | {
    __kind__: "SoundCloud";
    SoundCloud: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Tappytoon";
    Tappytoon: null;
} | {
    __kind__: "Lezhin";
    Lezhin: null;
};
export interface ProfileView {
    bio: string;
    principal: Principal;
    preferredLanguage?: ContentLanguage;
    country?: string;
    username: string;
    joinedAt: Timestamp;
    subtitlePreference: boolean;
    profileCompleted: boolean;
    fandom?: string;
}
export type LinkId = bigint;
export interface Link {
    id: LinkId;
    url: string;
    title: string;
    contentLanguage?: ContentLanguage;
    description: string;
    platform: Platform;
    mediaUrl?: string;
    genre?: Genre;
    addedAt: Timestamp;
    addedBy: Principal;
    category: Category;
    coverPhotoUrl?: string;
}
export enum Category {
    MANHWA = "MANHWA",
    BTS_LIVE = "BTS_LIVE",
    K_DRAMA = "K_DRAMA",
    BTS_SONGS = "BTS_SONGS",
    FANFICTION = "FANFICTION"
}
export enum ContentLanguage {
    Korean = "Korean",
    Spanish = "Spanish",
    Hindi = "Hindi",
    English = "English",
    French = "French"
}
export enum Genre {
    AU = "AU",
    EDM = "EDM",
    Pop = "Pop",
    Rap = "Rap",
    RnB = "RnB",
    Action = "Action",
    Mystery = "Mystery",
    Historical = "Historical",
    Drama = "Drama",
    Ballad = "Ballad",
    HipHop = "HipHop",
    Romance = "Romance",
    Fantasy = "Fantasy",
    Thriller = "Thriller",
    Comedy = "Comedy"
}
export interface backendInterface {
    addComment(postId: PostId, content: string): Promise<Comment>;
    addLink(title: string, description: string, url: string, platform: Platform, category: Category, genre: Genre | null, contentLanguage: ContentLanguage | null, coverPhotoUrl: string | null, mediaUrl: string | null): Promise<Link>;
    addToWatchlist(input: WatchlistInput): Promise<{
        __kind__: "ok";
        ok: WatchlistEntryView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createPost(content: string, hashtags: Array<string>): Promise<PostView>;
    deleteLink(id: LinkId): Promise<boolean>;
    editLink(id: LinkId, title: string, description: string, url: string, platform: Platform, category: Category, genre: Genre | null, contentLanguage: ContentLanguage | null, coverPhotoUrl: string | null, mediaUrl: string | null): Promise<boolean>;
    flagPost(id: PostId): Promise<boolean>;
    getComments(postId: PostId): Promise<Array<Comment>>;
    getLinks(category: Category | null): Promise<Array<Link>>;
    getPost(id: PostId): Promise<PostView | null>;
    getProfile(user: Principal): Promise<ProfileView | null>;
    getWatchlist(): Promise<Array<WatchlistEntryView>>;
    isInWatchlist(linkId: string): Promise<boolean>;
    likePost(postId: PostId): Promise<boolean>;
    listPosts(): Promise<Array<PostView>>;
    removeFromWatchlist(entryId: string): Promise<boolean>;
    searchByGenre(genre: Genre): Promise<Array<Link>>;
    searchByLanguage(language: ContentLanguage): Promise<Array<Link>>;
    searchLinks(keyword: string): Promise<Array<Link>>;
    setOnboarding(country: string | null, fandom: string | null, preferredLanguage: ContentLanguage | null, subtitlePreference: boolean): Promise<void>;
    setProfile(username: string, bio: string): Promise<void>;
}
import type { Category as _Category, ContentLanguage as _ContentLanguage, Genre as _Genre, Link as _Link, LinkId as _LinkId, Platform as _Platform, PostView as _PostView, ProfileView as _ProfileView, Timestamp as _Timestamp, WatchlistEntryView as _WatchlistEntryView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: PostId, arg1: string): Promise<Comment> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addLink(arg0: string, arg1: string, arg2: string, arg3: Platform, arg4: Category, arg5: Genre | null, arg6: ContentLanguage | null, arg7: string | null, arg8: string | null): Promise<Link> {
        if (this.processError) {
            try {
                const result = await this.actor.addLink(arg0, arg1, arg2, to_candid_Platform_n1(this._uploadFile, this._downloadFile, arg3), to_candid_Category_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg8));
                return from_candid_Link_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLink(arg0, arg1, arg2, to_candid_Platform_n1(this._uploadFile, this._downloadFile, arg3), to_candid_Category_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg8));
            return from_candid_Link_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async addToWatchlist(arg0: WatchlistInput): Promise<{
        __kind__: "ok";
        ok: WatchlistEntryView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0);
                return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0);
            return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPost(arg0: string, arg1: Array<string>): Promise<PostView> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1);
            return result;
        }
    }
    async deleteLink(arg0: LinkId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLink(arg0);
            return result;
        }
    }
    async editLink(arg0: LinkId, arg1: string, arg2: string, arg3: string, arg4: Platform, arg5: Category, arg6: Genre | null, arg7: ContentLanguage | null, arg8: string | null, arg9: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.editLink(arg0, arg1, arg2, arg3, to_candid_Platform_n1(this._uploadFile, this._downloadFile, arg4), to_candid_Category_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editLink(arg0, arg1, arg2, arg3, to_candid_Platform_n1(this._uploadFile, this._downloadFile, arg4), to_candid_Category_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async flagPost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.flagPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagPost(arg0);
            return result;
        }
    }
    async getComments(arg0: PostId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getLinks(arg0: Category | null): Promise<Array<Link>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLinks(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLinks(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: PostId): Promise<PostView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<ProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWatchlist(): Promise<Array<WatchlistEntryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return result;
        }
    }
    async isInWatchlist(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isInWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isInWatchlist(arg0);
            return result;
        }
    }
    async likePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async listPosts(): Promise<Array<PostView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPosts();
            return result;
        }
    }
    async removeFromWatchlist(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
    async searchByGenre(arg0: Genre): Promise<Array<Link>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByGenre(to_candid_Genre_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByGenre(to_candid_Genre_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchByLanguage(arg0: ContentLanguage): Promise<Array<Link>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByLanguage(to_candid_ContentLanguage_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByLanguage(to_candid_ContentLanguage_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchLinks(arg0: string): Promise<Array<Link>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchLinks(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchLinks(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async setOnboarding(arg0: string | null, arg1: string | null, arg2: ContentLanguage | null, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOnboarding(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOnboarding(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async setProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Category_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ContentLanguage_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentLanguage): ContentLanguage {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Genre_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Genre): Genre {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Link_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Link): Link {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Platform_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Platform): Platform {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileView_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileView): ProfileView {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContentLanguage]): ContentLanguage | null {
    return value.length === 0 ? null : from_candid_ContentLanguage_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Genre]): Genre | null {
    return value.length === 0 ? null : from_candid_Genre_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostView]): PostView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileView]): ProfileView | null {
    return value.length === 0 ? null : from_candid_ProfileView_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LinkId;
    url: string;
    title: string;
    contentLanguage: [] | [_ContentLanguage];
    description: string;
    platform: _Platform;
    mediaUrl: [] | [string];
    genre: [] | [_Genre];
    addedAt: _Timestamp;
    addedBy: Principal;
    category: _Category;
    coverPhotoUrl: [] | [string];
}): {
    id: LinkId;
    url: string;
    title: string;
    contentLanguage?: ContentLanguage;
    description: string;
    platform: Platform;
    mediaUrl?: string;
    genre?: Genre;
    addedAt: Timestamp;
    addedBy: Principal;
    category: Category;
    coverPhotoUrl?: string;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        contentLanguage: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.contentLanguage)),
        description: value.description,
        platform: from_candid_Platform_n17(_uploadFile, _downloadFile, value.platform),
        mediaUrl: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.mediaUrl)),
        genre: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.genre)),
        addedAt: value.addedAt,
        addedBy: value.addedBy,
        category: from_candid_Category_n23(_uploadFile, _downloadFile, value.category),
        coverPhotoUrl: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.coverPhotoUrl))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    preferredLanguage: [] | [_ContentLanguage];
    country: [] | [string];
    username: string;
    joinedAt: _Timestamp;
    subtitlePreference: boolean;
    profileCompleted: boolean;
    fandom: [] | [string];
}): {
    bio: string;
    principal: Principal;
    preferredLanguage?: ContentLanguage;
    country?: string;
    username: string;
    joinedAt: Timestamp;
    subtitlePreference: boolean;
    profileCompleted: boolean;
    fandom?: string;
} {
    return {
        bio: value.bio,
        principal: value.principal,
        preferredLanguage: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.preferredLanguage)),
        country: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.country)),
        username: value.username,
        joinedAt: value.joinedAt,
        subtitlePreference: value.subtitlePreference,
        profileCompleted: value.profileCompleted,
        fandom: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.fandom))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Korean: null;
} | {
    Spanish: null;
} | {
    Hindi: null;
} | {
    English: null;
} | {
    French: null;
}): ContentLanguage {
    return "Korean" in value ? ContentLanguage.Korean : "Spanish" in value ? ContentLanguage.Spanish : "Hindi" in value ? ContentLanguage.Hindi : "English" in value ? ContentLanguage.English : "French" in value ? ContentLanguage.French : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Wattpad: null;
} | {
    Netflix: null;
} | {
    Bato: null;
} | {
    Viki: null;
} | {
    Webtoon: null;
} | {
    YouTube: null;
} | {
    Spotify: null;
} | {
    MangaDex: null;
} | {
    Tapas: null;
} | {
    SoundCloud: null;
} | {
    Other: string;
} | {
    Tappytoon: null;
} | {
    Lezhin: null;
}): {
    __kind__: "Wattpad";
    Wattpad: null;
} | {
    __kind__: "Netflix";
    Netflix: null;
} | {
    __kind__: "Bato";
    Bato: null;
} | {
    __kind__: "Viki";
    Viki: null;
} | {
    __kind__: "Webtoon";
    Webtoon: null;
} | {
    __kind__: "YouTube";
    YouTube: null;
} | {
    __kind__: "Spotify";
    Spotify: null;
} | {
    __kind__: "MangaDex";
    MangaDex: null;
} | {
    __kind__: "Tapas";
    Tapas: null;
} | {
    __kind__: "SoundCloud";
    SoundCloud: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Tappytoon";
    Tappytoon: null;
} | {
    __kind__: "Lezhin";
    Lezhin: null;
} {
    return "Wattpad" in value ? {
        __kind__: "Wattpad",
        Wattpad: value.Wattpad
    } : "Netflix" in value ? {
        __kind__: "Netflix",
        Netflix: value.Netflix
    } : "Bato" in value ? {
        __kind__: "Bato",
        Bato: value.Bato
    } : "Viki" in value ? {
        __kind__: "Viki",
        Viki: value.Viki
    } : "Webtoon" in value ? {
        __kind__: "Webtoon",
        Webtoon: value.Webtoon
    } : "YouTube" in value ? {
        __kind__: "YouTube",
        YouTube: value.YouTube
    } : "Spotify" in value ? {
        __kind__: "Spotify",
        Spotify: value.Spotify
    } : "MangaDex" in value ? {
        __kind__: "MangaDex",
        MangaDex: value.MangaDex
    } : "Tapas" in value ? {
        __kind__: "Tapas",
        Tapas: value.Tapas
    } : "SoundCloud" in value ? {
        __kind__: "SoundCloud",
        SoundCloud: value.SoundCloud
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : "Tappytoon" in value ? {
        __kind__: "Tappytoon",
        Tappytoon: value.Tappytoon
    } : "Lezhin" in value ? {
        __kind__: "Lezhin",
        Lezhin: value.Lezhin
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AU: null;
} | {
    EDM: null;
} | {
    Pop: null;
} | {
    Rap: null;
} | {
    RnB: null;
} | {
    Action: null;
} | {
    Mystery: null;
} | {
    Historical: null;
} | {
    Drama: null;
} | {
    Ballad: null;
} | {
    HipHop: null;
} | {
    Romance: null;
} | {
    Fantasy: null;
} | {
    Thriller: null;
} | {
    Comedy: null;
}): Genre {
    return "AU" in value ? Genre.AU : "EDM" in value ? Genre.EDM : "Pop" in value ? Genre.Pop : "Rap" in value ? Genre.Rap : "RnB" in value ? Genre.RnB : "Action" in value ? Genre.Action : "Mystery" in value ? Genre.Mystery : "Historical" in value ? Genre.Historical : "Drama" in value ? Genre.Drama : "Ballad" in value ? Genre.Ballad : "HipHop" in value ? Genre.HipHop : "Romance" in value ? Genre.Romance : "Fantasy" in value ? Genre.Fantasy : "Thriller" in value ? Genre.Thriller : "Comedy" in value ? Genre.Comedy : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MANHWA: null;
} | {
    BTS_LIVE: null;
} | {
    K_DRAMA: null;
} | {
    BTS_SONGS: null;
} | {
    FANFICTION: null;
}): Category {
    return "MANHWA" in value ? Category.MANHWA : "BTS_LIVE" in value ? Category.BTS_LIVE : "K_DRAMA" in value ? Category.K_DRAMA : "BTS_SONGS" in value ? Category.BTS_SONGS : "FANFICTION" in value ? Category.FANFICTION : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WatchlistEntryView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WatchlistEntryView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Link>): Array<Link> {
    return value.map((x)=>from_candid_Link_n12(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ContentLanguage_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentLanguage): _ContentLanguage {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Genre_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): _Genre {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Platform_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): _Platform {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre | null): [] | [_Genre] {
    return value === null ? candid_none() : candid_some(to_candid_Genre_n6(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentLanguage | null): [] | [_ContentLanguage] {
    return value === null ? candid_none() : candid_some(to_candid_ContentLanguage_n9(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentLanguage): {
    Korean: null;
} | {
    Spanish: null;
} | {
    Hindi: null;
} | {
    English: null;
} | {
    French: null;
} {
    return value == ContentLanguage.Korean ? {
        Korean: null
    } : value == ContentLanguage.Spanish ? {
        Spanish: null
    } : value == ContentLanguage.Hindi ? {
        Hindi: null
    } : value == ContentLanguage.English ? {
        English: null
    } : value == ContentLanguage.French ? {
        French: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Wattpad";
    Wattpad: null;
} | {
    __kind__: "Netflix";
    Netflix: null;
} | {
    __kind__: "Bato";
    Bato: null;
} | {
    __kind__: "Viki";
    Viki: null;
} | {
    __kind__: "Webtoon";
    Webtoon: null;
} | {
    __kind__: "YouTube";
    YouTube: null;
} | {
    __kind__: "Spotify";
    Spotify: null;
} | {
    __kind__: "MangaDex";
    MangaDex: null;
} | {
    __kind__: "Tapas";
    Tapas: null;
} | {
    __kind__: "SoundCloud";
    SoundCloud: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Tappytoon";
    Tappytoon: null;
} | {
    __kind__: "Lezhin";
    Lezhin: null;
}): {
    Wattpad: null;
} | {
    Netflix: null;
} | {
    Bato: null;
} | {
    Viki: null;
} | {
    Webtoon: null;
} | {
    YouTube: null;
} | {
    Spotify: null;
} | {
    MangaDex: null;
} | {
    Tapas: null;
} | {
    SoundCloud: null;
} | {
    Other: string;
} | {
    Tappytoon: null;
} | {
    Lezhin: null;
} {
    return value.__kind__ === "Wattpad" ? {
        Wattpad: value.Wattpad
    } : value.__kind__ === "Netflix" ? {
        Netflix: value.Netflix
    } : value.__kind__ === "Bato" ? {
        Bato: value.Bato
    } : value.__kind__ === "Viki" ? {
        Viki: value.Viki
    } : value.__kind__ === "Webtoon" ? {
        Webtoon: value.Webtoon
    } : value.__kind__ === "YouTube" ? {
        YouTube: value.YouTube
    } : value.__kind__ === "Spotify" ? {
        Spotify: value.Spotify
    } : value.__kind__ === "MangaDex" ? {
        MangaDex: value.MangaDex
    } : value.__kind__ === "Tapas" ? {
        Tapas: value.Tapas
    } : value.__kind__ === "SoundCloud" ? {
        SoundCloud: value.SoundCloud
    } : value.__kind__ === "Other" ? {
        Other: value.Other
    } : value.__kind__ === "Tappytoon" ? {
        Tappytoon: value.Tappytoon
    } : value.__kind__ === "Lezhin" ? {
        Lezhin: value.Lezhin
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    MANHWA: null;
} | {
    BTS_LIVE: null;
} | {
    K_DRAMA: null;
} | {
    BTS_SONGS: null;
} | {
    FANFICTION: null;
} {
    return value == Category.MANHWA ? {
        MANHWA: null
    } : value == Category.BTS_LIVE ? {
        BTS_LIVE: null
    } : value == Category.K_DRAMA ? {
        K_DRAMA: null
    } : value == Category.BTS_SONGS ? {
        BTS_SONGS: null
    } : value == Category.FANFICTION ? {
        FANFICTION: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): {
    AU: null;
} | {
    EDM: null;
} | {
    Pop: null;
} | {
    Rap: null;
} | {
    RnB: null;
} | {
    Action: null;
} | {
    Mystery: null;
} | {
    Historical: null;
} | {
    Drama: null;
} | {
    Ballad: null;
} | {
    HipHop: null;
} | {
    Romance: null;
} | {
    Fantasy: null;
} | {
    Thriller: null;
} | {
    Comedy: null;
} {
    return value == Genre.AU ? {
        AU: null
    } : value == Genre.EDM ? {
        EDM: null
    } : value == Genre.Pop ? {
        Pop: null
    } : value == Genre.Rap ? {
        Rap: null
    } : value == Genre.RnB ? {
        RnB: null
    } : value == Genre.Action ? {
        Action: null
    } : value == Genre.Mystery ? {
        Mystery: null
    } : value == Genre.Historical ? {
        Historical: null
    } : value == Genre.Drama ? {
        Drama: null
    } : value == Genre.Ballad ? {
        Ballad: null
    } : value == Genre.HipHop ? {
        HipHop: null
    } : value == Genre.Romance ? {
        Romance: null
    } : value == Genre.Fantasy ? {
        Fantasy: null
    } : value == Genre.Thriller ? {
        Thriller: null
    } : value == Genre.Comedy ? {
        Comedy: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
